name: Deploy Frontend to Server

on:
  push:
    branches:
      - lavanya18  # Updated to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Ensure this matches the secret name

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@stagging.naaviverse.com << 'EOF'
            cd /home/ubuntu/Naaviverse-8
            ./deploy.sh lavanya18  # Pass the branch name directly
          EOF